{{- if .Values.checkoutService.create }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: checkout-availability
  namespace: {{ .Release.Namespace }}

spec:
  metrics:
    - name: checkout-fast-burn
      interval: 30s
      count: 3
      failureLimit: 1

      successCondition: len(result) > 0 && result[0] == 0
      failureCondition: len(result) > 0 && result[0] == 1

      provider:
        prometheus:
          address: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          query: |
            (
              slo:sli_error:ratio_rate1h{
                sloth_service="checkoutservice",
                sloth_slo="availability"
              } > bool 0.0144
            )
            *
            (
              slo:sli_error:ratio_rate5m{
                sloth_service="checkoutservice",
                sloth_slo="availability"
              } > bool 0.0144
            )
{{- end }}
