# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Continuous Integration - Main/Release"
on:
  push:
    # run on pushes to main or release/*
    branches:
      - main
      - release/*
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE'
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
      - 'terraform/**'
      - '.github/workflows/terraform-validate-ci.yaml'
      - 'helm-chart/**'
      - '.github/workflows/helm-chart-ci.yaml'

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ghcr.io/ryuichimatsuyama

jobs:
  build-and-push::
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ■ Buildxセットアップ
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # ■ GHCRログイン（ECRならここ変更）
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        id: version
        run: |
          VERSION="v$(date +'%Y.%m.%d')-${GITHUB_SHA::7}"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # ■ buildx bake + push
      - name: Build and push images
        uses: docker/bake-action@v7
        with:
          files: docker-bake.hcl
          push: true
        env:
          TAG: ${{ steps.version.outputs.version }}

      - name: Save version
        run: |
          echo "${{ steps.version.outputs.version }}" > /tmp/release-version
    
    outputs:
      version: ${{ steps.version.outputs.version }}

  release-marker:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push release marker
        run: |
          docker pull alpine:3.22

          docker tag alpine:3.22 \
            ${{ env.IMAGE_PREFIX }}/release:${{ needs.build-and-push.outputs.version }}

          docker push \
            ${{ env.IMAGE_PREFIX }}/release:${{ needs.build-and-push.outputs.version }} 
