# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Continuous Integration - Pull Request"
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - 'kustomize/**'
      - '.github/workflows/kustomize-build-ci.yaml'
      - 'terraform/**'
      - '.github/workflows/terraform-validate-ci.yaml'
      - 'helm-chart/**'
      - '.github/workflows/helm-chart-ci.yaml'

# Ensure this workflow only runs for the most recent commit of a pull-request
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-dotnet@v5
      env:
        DOTNET_INSTALL_DIR: "./.dotnet"
      with:
        dotnet-version: '10.0'
    - uses: actions/setup-go@v6
      with:
        go-version: '1.26'
    - name: Go Unit Tests
      timeout-minutes: 10
      run: |
        for GO_PACKAGE in "shippingservice" "productcatalogservice" "frontend/validator"; do
          echo "Testing $GO_PACKAGE..."
          pushd src/$GO_PACKAGE
          go test
          popd
        done
    - name: C# Unit Tests
      timeout-minutes: 10
      run: |
        dotnet test src/cartservice/

  deployment-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: code-tests
    strategy:
      matrix:
        profile: ["local-code"]
      fail-fast: true
    steps:
    - uses: actions/checkout@v6
      with:
        ref: ${{github.event.pull_request.head.sha}}
    - name: Login to GHCR
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Build Docker images
      uses: hiberbee/github-action-skaffold@1.27.0
      with:
        command: build
        repository: ghcr.io/${{ github.repository }}/refs/pull/${{ github.event.pull_request.number }}
        tag: ${{ github.event.pull_request.number }}
        profile: network-policies
      env:
        PR_NUMBER: ${{ github.event.pull_request.number }}
    # - name: Build PR images to ghcr
    #   timeout-minutes: 20
    #   run: |
    #     NAMESPACE="pr${PR_NUMBER}"
    #     echo "NAMESPACE=$NAMESPACE" >> $GITHUB_ENV

    #     echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    #     echo Deploying application
    #     skaffold config set --global local-cluster false
    #     skaffold build --default-repo=ghcr.io/${{ github.repository }}/refs/pull/$PR_NUMBER --tag=$PR_NUMBER -p network-policies
    #   env:
    #     PR_NUMBER: ${{ github.event.pull_request.number }}
    - name: Comment EXTERNAL_IP
      timeout-minutes: 5
      env:
          COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          curl \
            -X POST \
            $COMMENTS_URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "🚲 PR staged at '"http://${EXTERNAL_IP}"'"}'
          sleep 60
