name: PR Environment Test

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  verify-pr-environment:
    name: Verify PR Environment
    runs-on: ubuntu-24.04

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ vars.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region "${{ vars.AWS_REGION }}" \
            --name "${{ vars.EKS_CLUSTER_NAME }}"

      - name: Check identity
        run: |
          aws sts get-caller-identity

      - name: Check Kubernetes RBAC
        run: |
          kubectl auth can-i get applications.argoproj.io -n argocd
          kubectl auth can-i get appprojects.argoproj.io -n argocd
          kubectl auth can-i delete applications.argoproj.io -n argocd

      - name: Find PR Application
        run: |
          APP="pr-${{ github.event.pull_request.number }}"

          kubectl get application "$APP" \
            -n argocd \
            -o wide
